### ISSUE TITLE
Release 0.1.1 Checklist. 

### ISSUE THREAD

**Issue by wksavageschool** [WkSavage/N.T.C-Hollowstone#8]
- [x] Balancing mobs 
  - [x]  Bees (More types!)
  - [x] Bats (Less Damage, slightly slower, low break chance)
  - [x] Carp (Slightly Higher Break chance)
  - [x] Bears (Hudson, the admin use bear)
  - [x] Combat Drones (Nerf Laser, slightly slower)
  - [x] Vox and Taj brute damage boost (They have claws, they should do more)
  - [x] Vox warn pressure set to 0 (Really no change)
  - [x] Adds Vox Pariah as a playable Vox subspecies (Loses low pressure advantages, slightly slower, Nerfs leap to knock both people over.)
  - [x] Small species buffs that correlate with lore (Beanzie and Mango, I need your help on this one!) 
- [x] Balancing weapons
  - [x] Relook at the taser (Think it's fine, may reduce stun chance a small bit) 
  - [x] High Power Stun Baton (Old UT thing. Would be in code red armory. Higher stun chance, runs out of charge faster)
  - [x] Crossbow nerf
  - [x] Look into each projectile type and the damage outposts (See Below)
  - [x] Energy
  - [x] Laser
  - [x] Ballistics
  - [x] Special 
- [x] Random Event Balance 
  - [x] Meteors! (Reduceds the amount of meteors from meteor wave.)
- [x] Air and Fire alarm sprites 
- [x] Port of BS12 Spider Sprites
- [x] Get Beanzie's Cloak to work
- [x] Get Rikers Coat in the code (I need to be told what the fucking Sprite is)
- [x] Port of Aurora fixes.
  - [x] Fire Fixes
  - [x] Mag-Locks Update
  - [x] Race fixes (That one weird ant race)
  - Vaurca, makes them resistance to electric shock and walking on glass.
  - Eye damage from flashes
  - [x] Vampire can suck from blood packs 
  - [x] Adrenaline Implant from TC uplink
  - [x] Fix for enthralling not working on LI-d people
  - [x] Fix a LI-s duplicate definition
- [x] Metis Cigarettes
- [x] Laptop Vendors and Metis Laptop Code.
- [x] CCIA Equip Preset (One click CCIA outfit)
  - [x] NTIA Equip Preset?
- [x] Vine Sprite Updates (Thanks to Beanzie)
- [x] Fix Wiki Buttons on Client. 
- [x] Verb Ports
  - [x] Clean Verb for admins.
  - [x] Default Lanuage client verb.
  - [x] Add Reagents under the VV panel
- [x] FINALLY A CHANGELOG. ABOUT TIME.

**Comment by wksavageschool** [comment]
Please leave suggestions down here.

**Comment by wksavageschool** [comment]
This is the final update list for 0.1.1

**Comment by WkSavage** [comment]
bonus fixes. thanks to our buds 
the aurora dev team

**Comment by WkSavage** [comment]
merged. missing content
- regent VV not added
- wiki buttons (date for that tbd)
